### ISSUE TITLE
Tables with composite foreign keys have issues during data ingest

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/pdb-ihm#174]
Data from user uploaded mmCIF file is converted to JSON and ingested into ermrest in the beginning of the workflow. Some tables have references with composite foreign keys that combine RID (internal to ermrest) and ID (coming from mmCIF). For example, `ihm_modeling_protocol.software_id` (from mmCIF) and `ihm_modeling_protocol.Software_RID` (internal to ermrest) point to `software.pdbx_ordinal` (from mmCIF) and `software.RID` (internal to ermrest). 

During data ingest from mmCIF (via JSON), the `id` value is properly populated because that information is available from the mmCIF and JSON files, but the `RID` value is left empty. Due to this, chaise does not properly display this information (see entries `D_2-S4AJ` on dev and `D_2-XF1G` on production). It is not clear if the `id` value from user-submitted mmCIF file is correctly propagated to the system generated mmCIF file in subsequent steps of the workflow. If it is not, then user-provided information is lost during the workflow.

**Comment by svoinea** [comment]
The code exited, but it had bug. I fixed it and it should work on the `dev` VM.

**Comment by brindakv** [comment]
@svoinea Has this been deployed on production?

**Comment by svoinea** [comment]
Yes.
