### ISSUE TITLE
common deployment workflow

### ISSUE THREAD

**Issue by tgarello** [informatics-isi-edu/pdb-ihm#223]
https://github.com/informatics-isi-edu/protein-database/blob/d2576fd33b3e2d2cf8d108daca0fbd8fc31d77a9/scripts/ubuntu/workflow-common/deploy-common.sh#L30C1-L30C33

hello,

I attempted to follow scripts/ubuntu/workflow-dev.

I encountered the following error in the above deployment command :
`cp: cannot stat '/home/isrddev/python-ihm/util/make-mmcif.py': No such file or directory`

After check, there was a breaking change in python-ihm. _util/make-mmcif.py_ has been renamed to _ihm/util/make_mmcif.py_

cf. https://github.com/ihmwg/python-ihm/commit/b476d4dea3d3b3d3ce5ea3877eff5f46cdac8ca7

**Comment by tgarello** [comment]
also the isrd software library is missing for the deploy-common.sh
it supposed to be here : /home/isrddev/protein-database/scripts/ubuntu/lib/pdb-software-lib.sh

but I imagine it may be deliberate

**Comment by hongsudt** [comment]
The goal for the deployment workflow is to cover the deployment of backend processing pipeline, not the deriva software stack. If you are interested in setting up the dependencies of tools used in processing pipeline, then this is the place to look (e.g. if we are going to replicate the tools in here with model archive).
