### ISSUE TITLE
Provide utility for querying via ermrest API

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/pdb-ihm#246]
This will help with creating DOIs and wwPDB DOI landing pages. 

Query details

For all entries with `entry.Workflow_Status` == `REL`, get the following information: 

 - `entry.Accession_Code` (single value, text)
 - `entry.Workflow_Status` (single value, text)
 - `struct.title` (single value, text)
 - `citation.pdbx_database_id_DOI` when `citation.id` == 1 (single value, text)
 - `audit_author.name` (get values from all rows in the table and create a comma separated list of all values)
 - `entry.Deposit_Date` (single value, yyyy-mm-dd)
 - `entry.Release_Date` (single value, yyyy-mm-dd)
 - `Entry_Latest_Archive.Submission_Time`

For all entries with `entry.Workflow_Status` == `HOLD`, get the following information: 

 - `entry.Accession_Code` (single value, text)
 - `entry.Workflow_Status` (single value, text)
 - `struct.title` (single value, text)
 - `audit_author.name` (get values from all rows in the table and create a comma separated list of all values)
 - `entry.Deposit_Date` (single value, yyyy-mm-dd)

**Comment by svoinea** [comment]
[client.txt](https://github.com/user-attachments/files/16882554/client.txt)
The file extension should be changed to `.py`, as github does not allow uploading Python files.

To run:
```
python3 client.py
```

**Comment by brindakv** [comment]
Thanks @svoinea. 

The `audit_author.name` needs to to be a comma-separated list of values from all rows in the table for that entry. Could you please provide the updated query that takes care of that? 

Additionally, can the keys in the output json file be set to `table_name.column_name` instead of just the `column_name`?

**Comment by svoinea** [comment]
[client.txt](https://github.com/user-attachments/files/16901656/client.txt)

While using aliases in the query output is a feature supported by `ermrest`, grouping values is not.
In the uploaded file, I have defined a Python function `def group_author(rows)` that is doing the post-processing of the queries output for the `audit_author.name`.
While `,` is already part of the name (separating the first name from the last name), I was using `; ` as separator between the names of the audit_author.

**Comment by brindakv** [comment]
Thanks @svoinea. It is ok to use `;` are separator.

**Comment by piehld** [comment]
Thank you for the very helpful script @svoinea! This is near perfect to what we need for our DOI registration purposes, but I just realized there is one more detail we need: `last_revision_date`.

@brindakv indicated that the table and column to use would be `Entry_Latest_Archive.Submission_Time`. Is it possible to add this detail into the returned results as well?

**Comment by brindakv** [comment]
@svoinea `Entry_Latest_Archive.Submission_Time` is only needed for entries with `entry.Workflow_Status == REL`. I updated the comment above.

**Comment by piehld** [comment]
@svoinea BTW—if this proves to be too complicated to add, then don't worry about spending too much time on it. We can rely on the `released_structures_last_modified_dates.json.gz` files instead.

**Comment by svoinea** [comment]
[client.txt](https://github.com/user-attachments/files/16948570/client.txt)
I have attached the new script with the `last_revision_date`.
Example of how the `REL` entries will be displayed now:
```
    {
        "entry.Accession_Code": "9A83",
        "entry.Workflow_Status": "REL",
        "entry.Deposit_Date": "2024-02-05",
        "entry.Release_Date": "2024-06-21",
        "last_revision_date": "2024-08-08T14:00:00-07:00",
        "struct.title": "Encounter complex in the cross-modular condensation step of the Tomaymycin NRPS system: complex of the substrate-loaded peptidyl-carrier-protein domain from the TomA module (APCP-load) with the adaptor (BN91) of the TomB module",
        "citation.pdbx_database_id_DOI": "10.1126/sciadv.adm9404",
        "audit_author.name": "Karanth, M.N.; Kirkpatrick, J. P.; Carlomagno, T."
    },
```

**Comment by piehld** [comment]
Thank you, @svoinea!

**Comment by brindakv** [comment]
@svoinea The query returns 160 `REL` entries and 9 `HOLD` entries on production. These numbers are incomplete. We have 335 `REL` and 9 `HOLD` entries on production right now.

**Comment by piehld** [comment]
@brindakv, to clarify, the current query actually returns 306 total entries. The 169 that I sent you was the list after removing the 137 that were just recently added 137.

In either case though, there are still 29 missing.

**Comment by brindakv** [comment]
@piehld If you use the latest `client.txt` file that @svoinea provided, you will get only 169 entries (160 `REL` and 9 `HOLD`). This is because the join with `Entry_Latest_Archive` takes care of only retrieving the entries that have been archived (same function as comparing with the holdings file). 

Considering that there are 198 REL entries in `Entry_Latest_Archive`, we are still missing 38 entries.

**Comment by hongsudt** [comment]
Here is the query that does a left join instead of join, so missing values will return as null.
```
https://data.pdb-dev.org/ermrest/catalog/1/attributegroup/E:=PDB:entry/Workflow_Status=REL/LA:=left(id)=(PDB:Entry_Latest_Archive:Entry)/$E/S:=left(id)=(PDB:struct:entry_id)/$E/C:=left(id)=(PDB:citation:structure_id)/$E/A:=left(id)=(PDB:audit_author:structure_id)/$E/E:id;E:Accession_Code,E:Workflow_Status,E:Deposit_Date,E:Release_Date,LA:Submission_Time,S:title,C:pdbx_database_id_DOI,A:name
```

**Comment by svoinea** [comment]
[client.txt](https://github.com/user-attachments/files/16971518/client.txt)
Uploaded the updated script.

**Comment by hongsudt** [comment]
@piehld please use the template in this client script to interact with pdb-dev server: https://github.com/informatics-isi-edu/protein-database/blob/master/pdb_dev/tools/get_doi_entries.py

please make sure to set up `dcctx` as stated.

There are 2 functions that you can use for different REL and HOLD. 

@brindakv you can also run the script. The default server is production, but you can change it to any of our catalog.

**Comment by piehld** [comment]
Thank you both, @svoinea and @hongsudt!
